name:                variadic
version:             0.0.0.0
github:              "estatico/variadic"
license:             BSD3
author:              "Cary Robbins"
maintainer:          "carymrobbins@gmail.com"
copyright:           "2021 Estatico Studios LLC"

extra-source-files:
- CHANGELOG.md
- testdata/**

synopsis:            Abstractions for working with variadic functions
category:            Control

description:         Please see the README on GitHub at <https://github.com/estatico/variadic#readme>

ghc-options:
- -Wall

dependencies:
- base >= 4.7 && < 5
- mmorph >= 1.1.3 && < 1.2
- mtl >= 2.2.2 && < 2.3

library:
  source-dirs: src

tests:
  variadic-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - variadic
    - containers
    - hspec
    - hspec-expectations-lifted
    - process

benchmarks:
  variadic-benchmark:
    main:               Bench.hs
    source-dirs:        bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - variadic
    - criterion
